FollettSchoolSolutions/perfmon4j-reports

- pom.xml
- src/main/java/org/perfmon4j/reports/app/data/ChartVo.java
- src/main/java/org/perfmon4j/reports/app/data/SeriesVo.java
- src/main/java/org/perfmon4j/reports/app/entity/Chart.java
- src/main/java/org/perfmon4j/reports/app/entity/Series.java
- src/main/java/org/perfmon4j/reports/app/service/ChartService.java
- src/main/webapp/components/chart/chart.html
- src/main/webapp/components/chart/chartController.js
- src/main/webapp/components/chart/chartSeries.html
- src/main/webapp/components/chart/chartSeriesController.js
- src/main/webapp/components/chart/chartSeriesDirective.js
- src/main/webapp/components/home/home.html
- src/main/webapp/components/home/homeController.js
- src/main/webapp/css/home.css
- src/main/webapp/services/chartService.js
- src/main/webapp/services/dataSourceService.js
Merged the persisting of charts into develop.
> Manual merge of persisting charts with develop

- src/main/webapp/components/chart/chartController.js
Chart times are in hours and minutes if range is less than 24 hours and in y-m-dTh:m if greater than 24 hours or a fixed range.
> Fixes to chart time display

- src/main/webapp/components/chart/chartSeriesController.js
- src/main/webapp/services/dataSourceService.js
Fixes how multiple systems limit categories.
> Limit Categories

- src/main/webapp/components/chart/chartController.js
Adds a zoom window when a user queries for more than 2 hours worth of data. Also cleans up some datetime code that I had written previously.
> Zoom window

- src/main/webapp/components/chart/chartController.js
Resolves an issue where the Y Axis goes negative on occasion in the chart.
> Scale Y Axis

- src/main/java/org/perfmon4jreports/app/data/SeriesVo.java
- src/main/java/org/perfmon4jreports/app/entity/Series.java
- src/main/webapp/components/chart/chart.html
- src/main/webapp/components/chart/chartController.js
- src/main/webapp/components/chart/sideNavController.js
- src/main/webapp/components/home/home.html
- src/main/webapp/components/home/homeController.js
- src/main/webapp/services/chartService.js
LIST OF BUG FIXES (?'s are future fixes)
-updated viewing a chart with new multiple systems code
-updated viewing a chart - now shows the title
-secondary axis is now persisted
-refresh home page when deleting a chart
-delete icon now matches the color scheme
?save confirmation without render - UNSOLVED (added issue in GH)
?weird IDs - DB is automatically doing this to balance the index tree
?save button once - SAVE after initial save needs to be UPDATE
-testing multiple systems - works
-testing multiple series - works
> Dev fix mergestorm5000

- src/main/webapp/components/appController.js
- src/main/webapp/components/home/home.html
- src/main/webapp/components/home/homeController.js
- src/main/webapp/css/home.css
- src/main/webapp/index.html
- src/main/webapp/services/chartService.js
Added all the UI/UX fixes to the Home page.
> S 19428 home page ui fixes

- src/main/webapp/components/chart/chart.html
- src/main/webapp/components/chart/chartController.js
- src/main/webapp/components/chart/chartSeries.html
- src/main/webapp/components/chart/chartSeriesController.js
- src/main/webapp/css/chart.css
- src/main/webapp/css/chartSeries.css
Most of the tasks from S-19441 are fixed. Made notes on VersionOne to address issues that may have came up while fixing them.
> Fixed a majority of the tasks created for S-19941

- src/main/java/org/perfmon4jreports/app/data/ChartVo.java
- src/main/java/org/perfmon4jreports/app/entity/Chart.java
- src/main/webapp/components/chart/advancedOptionsDialog.html
- src/main/webapp/components/chart/chart.html
- src/main/webapp/components/chart/chartController.js
- src/main/webapp/css/advancedOptionsDialog.css
- src/main/webapp/css/chart.css
- src/main/webapp/index.html
- src/main/webapp/services/chartService.js
Updates the chart to use axis labels and rescale when zooming.
> Chart label enhancements

- src/main/webapp/components/chart/chart.html
- src/main/webapp/components/chart/sideNavController.js
> fixed the togglebutton showing up in the view page

- src/main/webapp/css/home.css
The home page divs are now responsive to screen size change.
> responsive home page

- .openshift/config/standalone.xml
> deploy fix

- README.md
> add updated readme to master

- src/main/webapp/components/chart/chart.html
- src/main/webapp/components/chart/chartController.js
- src/main/webapp/components/chart/chartSeries.html
- src/main/webapp/components/chart/chartSeriesController.js
- src/main/webapp/services/chartService.js
all the UI dropdowns are now tied to watcher functions in the controller instead of using ng-change. this will make edit much easier.
> Refactor chart variables

- src/main/webapp/index.jsp
removed home button, logo is now home button link
> removed home button. toolbar logo is now the home button

- src/main/java/org/perfmon4jreports/app/entity/Chart.java
- src/main/java/org/perfmon4jreports/app/service/ChartService.java
- src/main/webapp/components/chart/chart.html
- src/main/webapp/components/chart/chartController.js
- src/main/webapp/components/home/home.jsp
- src/main/webapp/components/home/homeController.js
- src/main/webapp/css/home.css
- src/main/webapp/services/chartService.js
details:
* lists of charts are now sorted alphabetically by their name
* there is a new checkbox in the create chart for making it publicly accessible
* there is a new list of public charts in the user home page
* there is a list of public charts in the home page before the user logs in
> Sorting / Public Access

- src/main/webapp/components/chart/chartController.js
- src/main/webapp/components/datasource/dataSourceController.js
> fixed edit

- src/main/webapp/services/chartService.js
> fixed duplicate

- src/main/java/org/json/CDL.java
- src/main/java/org/json/Cookie.java
- src/main/java/org/json/CookieList.java
- src/main/java/org/json/HTTP.java
- src/main/java/org/json/HTTPTokener.java
- src/main/java/org/json/JSONArray.java
- src/main/java/org/json/JSONException.java
- src/main/java/org/json/JSONML.java
- src/main/java/org/json/JSONObject.java
- src/main/java/org/json/JSONString.java
- src/main/java/org/json/JSONStringer.java
- src/main/java/org/json/JSONTokener.java
- src/main/java/org/json/JSONWriter.java
- src/main/java/org/json/Property.java
- src/main/java/org/json/README
- src/main/java/org/json/XML.java
- src/main/java/org/json/XMLTokener.java
- src/main/java/org/perfmon4jreports/app/service/ChartService.java
- src/main/java/org/perfmon4jreports/app/sso/User.java
- src/main/webapp/components/home/home.jsp
public chart listing in home page now includes the creator's name in the title
> creator names for public charts

- src/main/webapp/components/chart/chart.html
- src/main/webapp/components/chart/chartController.js
- src/main/webapp/components/chart/sideNavController.js
- src/main/webapp/css/home.css
- src/main/webapp/index.jsp
fix for index.jsp:
```
<body layout="row">
<div layout-fill layout="column" ...>
...
<md-content layout=”row”>
```
> Dan 'The Man' Watling found a fix for this :)

- src/main/java/org/perfmon4jreports/app/service/ChartService.java
- src/main/webapp/components/home/home.jsp
- src/main/webapp/css/home.css
When a datasource is not reachable, the chart entry in the list of charts in the home page is greyed out as well as the edit and duplicate buttons. The delete button is still accessible, however.
> Chart datasource connection check

- src/main/webapp/components/datasource/dataSourceController.js
- src/main/webapp/components/datasource/datasource.html
- src/main/webapp/components/datasource/editDataSource.html
- src/main/webapp/components/home/home.jsp
- src/main/webapp/css/home.css
GUI of add/edit datasources has been rewritten to use Google's design standards (it looks really nice). There is now a info icon/button next to the URL field that, when clicked, takes the user to the wiki page describing the datasource URL syntax.
> Datasource url infobox

- src/main/java/org/perfmon4jreports/app/service/ChartService.java
- src/main/webapp/components/home/homeController.js
- src/main/webapp/services/dataSourceService.js
@Rayfucious helped me find a good solution for my concurrency issues with so many http promises
> Datasource connection check rewrite

- src/main/webapp/components/chart/advancedOptionsDialog.html
- src/main/webapp/components/chart/chart.html
- src/main/webapp/components/chart/chartController.js
- src/main/webapp/components/chart/chartSeries.html
- src/main/webapp/components/datasource/datasource.html
- src/main/webapp/components/datasource/editDataSource.html
- src/main/webapp/css/chartSeries.css
- src/main/webapp/css/home.css
- removed some lingering references to ng-md-icon
- fixed up the custom label dialog in create chart
- hid time adjustment div in chart view from create and edit
> misc ui fixes

- src/main/java/org/perfmon4jreports/app/service/ChartService.java
- src/main/webapp/services/dataSourceService.js
story: https://github.com/FollettSchoolSolutions/perfmon4j-reports/issues/143
> changing a datasource url now batch updates all the charts using that datasource
